[build]
command = "pnpm run build"
publish = "build"

[[redirects]]
from = "/cell-workshop/*"
to = "https://glistening-bombolone-42394b.netlify.app/:splat"
status = 200

[[redirects]]
from = "/stats/*"
to = "https://zelo-stats.netlify.app/:splat"
status = 200

[[redirects]]
from = "/ant/*"
to = "https://leafy-crepe-58711a.netlify.app/:splat"
status = 200
